apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gatling-execution
  name: gatling-execution
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatling-execution
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gatling-execution
    spec:
      containers:
      - image: gatling-execution:latest
        name: gatling-execution
        resources: {}
        ports:
          - containerPort: 3000
status: {}
